[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = ["@openzeppelin=lib/openzeppelin-contracts",
    "@chainlink/contracts/src/v0.8/shared/interfaces/ = /lib/chainlink-brownie-contracts/contracts/src/v0.8/interfaces/"
]

[invariant]
runs = 128
depth = 128
fail_on_revert = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
